### ISSUE TITLE
Duplicate Plugins?

### ISSUE THREAD

**Issue by Dulanic** [cvarta/deluge-extractor#12]
When using this plugin, it adds itself again to the thin client every time it reboots?

![image](https://user-images.githubusercontent.com/2948206/41554187-b46854ec-72f9-11e8-961b-be510a2acedf.png)

**Comment by chrishuan9** [comment]
Did you see the REAMDE file. There is a section about incompatibility if your thin client is running a different version of python or deluge compared to the server: [Link](https://github.com/cvarta/deluge-extractor#client-server-setups)

**Comment by Dulanic** [comment]
Same version. Both use 2.7.

**Comment by Dulanic** [comment]
deluge-1.3.15-win32-py2.7.exe was used... so 2.7
Linux deluged - Python 2.7.14
