### ISSUE TITLE
Can't enable plugin

### ISSUE THREAD

**Issue by TrySpace** [cvarta/deluge-extractor#23]
WIndows 10 x64.

Tried things like enabling the GTK ui, reinstalling python 2.7, but no difference.

Whenever I check the mark in the plugins for the extractor, and click apply, it will unselect, there must be something going wrong with loading, other plugins do load.

I suspect this might happen because the windows version of deluge is not yet the latest version.

**Comment by MiamiFinsFan13** [comment]
Having the same issue.....i know for AutoRemovePlus the solution to the same problem was to remove the egg and conf file and add it again. gonna try that and see if it helps.

**Comment by chrishuan9** [comment]
@TrySpace @MiamiFinsFan13  could you tell me which version of Deluge you were using? 1.3.X branch or 2.X branch?
The current plugin only really works with 1.3.X.

**Comment by chrishuan9** [comment]
Thanks to @d8ahazard  work the plugin also works with 2.0.X branch of deluge.
