### ISSUE TITLE
Doesn't work - Raspberry pi 3 with Deluge daemon and deluge-web both running

### ISSUE THREAD

**Issue by suckerfish** [cvarta/deluge-extractor#5]
Python version 2.7
7zip installed - I use it just fine manually
plugin in the right directory. 
WebUi sees the plugin and I can adjust configuration without issue. 
simpleextractor.conf gets created in the deluge config folder no problem

Just nothing gets extracted.

Are there logs stored somewhere? Can this be debugged somehow?

**Comment by chrishuan9** [comment]
## Workaround ##
try installing the following package: `unrar` using `apt-get install unrar`

at the moment it uses 7zip on windows and unrar cli on unix system. You can also modify the `core.py` and change the parts to use your favorite extraction tool.

**Comment by suckerfish** [comment]
Thank you. That was most likely it. I have since moved my Deluge client to a different box and it started working right away. most likely due to the fact that unrar was installed on that box.
